require 'net/http'
require 'open-uri'
require 'json'
require 'httparty'
require 'pry'

require_relative '../lib/api.rb'
require_relative '../lib/character.rb'
require_relative '../lib/cli.rb'
require_relative '../lib/film.rb'
require_relative '../lib/planet.rb'